spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_UPPER=FALSE
    username: sa
    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  batch:
    job:
      enabled: false

jwt:
  secret-key: "this-is-a-temporary-secret-key-for-local-tests-1234567890"
  access-token-expired: 3600000
  refresh-token-expired: 86400000

operation:
  base-url: http://localhost:9999

discord:
  webhook:
    url: "https://discord.com/api/webhooks/test/test"
